# Generated by Django 6.1.1 on 2026-10-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
    ]
